export enum PERMISSIONS {
  INVITE_USER = 'INVITE_USER',
  VIEW_USER = 'VIEW_USER',
  INVITE_STUDENT = 'INVITE_STUDENT',
  VIEW_STUDENT = 'VIEW_STUDENT',
  EDIT_STUDENT = 'EDIT_STUDENT',
  VIEW_DEPARTMENT = 'VIEW_DEPARTMENT',
  EDIT_DEPARTMENT = 'EDIT_DEPARTMENT',
  VIEW_CYCLE = 'VIEW_CYCLE',
  EDIT_CYCLE = 'EDIT_CYCLE',
  VIEW_VACANCY = 'VIEW_VACANCY',
  EDIT_VACANCY = 'EDIT_VACANCY',
  VIEW_REPORT = 'VIEW_REPORT', // Both normal and final reports.
  EDIT_REPORT = 'EDIT_REPORT',
  VIEW_COMISSION_OFFICE = 'VIEW_COMISSION_OFFICE',
  EDIT_COMISSION_OFFICE = 'EDIT_COMISSION_OFFICE'
}

const ADMIN_DEFAULT_PERMISSIONS: PERMISSIONS[] = [...Object.values(PERMISSIONS)]

const MEMBER_DEFAULT_PERMISSIONS: PERMISSIONS[] = [
  PERMISSIONS.VIEW_STUDENT,
  PERMISSIONS.VIEW_DEPARTMENT,
  PERMISSIONS.VIEW_CYCLE,
  PERMISSIONS.VIEW_VACANCY,
  PERMISSIONS.VIEW_COMISSION_OFFICE,
  PERMISSIONS.EDIT_COMISSION_OFFICE,
  PERMISSIONS.VIEW_REPORT,
  PERMISSIONS.EDIT_REPORT
]

export interface Roles {
  admin: PERMISSIONS[]
  member: PERMISSIONS[]
  base: PERMISSIONS[]
}

export const DEFAULT_ROLE_PERMISSIONS: Roles = {
  admin: ADMIN_DEFAULT_PERMISSIONS,
  member: MEMBER_DEFAULT_PERMISSIONS,
  base: [] as PERMISSIONS[]
}
