export enum PERMISSIONS {
  INVITE_USER = 'INVITE_USER',
  VIEW_USER = 'VIEW_USER',
  INVITE_STUDENT = 'INVITE_STUDENT',
  VIEW_STUDENT = 'VIEW_STUDENT',
  EDIT_STUDENT = 'EDIT_STUDENT',
  VIEW_DEPARTMENT = 'VIEW_DEPARTMENT',
  EDIT_DEPARTMENT = 'EDIT_DEPARTMENT'
}

const ADMIN_DEFAULT_PERMISSIONS: PERMISSIONS[] = [...Object.values(PERMISSIONS)]

const MEMBER_DEFAULT_PERMISSIONS: PERMISSIONS[] = [
  PERMISSIONS.VIEW_STUDENT,
  PERMISSIONS.VIEW_DEPARTMENT
]

export interface Roles {
  admin: PERMISSIONS[]
  member: PERMISSIONS[]
  base: PERMISSIONS[]
}

export const DEFAULT_ROLE_PERMISSIONS: Roles = {
  admin: ADMIN_DEFAULT_PERMISSIONS,
  member: MEMBER_DEFAULT_PERMISSIONS,
  base: [] as PERMISSIONS[]
}
